# Generated by Django 4.0.3 on 2022-04-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0006_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('comment_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.usermodel')),
            ],
            options={
                'db_table': 'group_posts_comments',
            },
        ),
        migrations.CreateModel(
            name='GroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
                ('group_description', models.CharField(max_length=50)),
                ('group_joining_link', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='TempPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp_images/')),
            ],
            options={
                'db_table': 'temp_post',
            },
        ),
        migrations.CreateModel(
            name='UserModelGroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
                ('primary', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_api.groupsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.usermodel')),
            ],
            options={
                'db_table': 'user_groups',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='PostCommentReplayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_text', models.CharField(max_length=1000)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_api.grouppostcommentsmodel')),
                ('replay_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.usermodel')),
            ],
            options={
                'db_table': 'comment_replay',
            },
        ),
        migrations.AddField(
            model_name='groupsmodel',
            name='user_id',
            field=models.ManyToManyField(related_name='u_g', through='groups_api.UserModelGroupsModel', to='user_api.usermodel'),
        ),
        migrations.CreateModel(
            name='GroupPostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=1000)),
                ('post_type', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents/')),
                ('likes', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_api.groupsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.usermodel')),
            ],
            options={
                'db_table': 'group_posts',
            },
        ),
        migrations.AddField(
            model_name='grouppostcommentsmodel',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_api.grouppostsmodel'),
        ),
    ]
