# Generated by Django 4.0.3 on 2022-04-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
