# Generated by Django 4.0.3 on 2022-04-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_rename_password_usermodel_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
