# Generated by Django 4.0.3 on 2022-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
