# Generated by Django 4.0.3 on 2022-04-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
